listen_addresses: "0.0.0.0:3000"
web_ui: enable-for-all
cors: true

postgres:
  connection_string: "${DATABASE_URL}"
  default_srid: 3857
  auto_bounds: quick
  auto_publish:
    from_schemas:
      - gis_data
    tables:
      source_id_format: "{table}"
      id_columns:
        - fid
      clip_geom: true
      buffer: 64
      extent: 4096
    functions: false
