/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ヘルスチェック */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** プロジェクト一覧 */
        get: operations["listProjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/layers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** レイヤ一覧 */
        get: operations["listLayers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/layers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** レイヤ削除 (結果セットが空になれば結果セットも削除) */
        delete: operations["deleteLayer"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/layers/{id}/attribute-values": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 属性の値候補一覧 (条件検索 UI 用) */
        get: operations["listLayerAttributeValues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/result-sets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 結果セット削除 (子の結果レイヤも削除) */
        delete: operations["deleteResultSet"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/layers/{id}/features/{featureId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** フィーチャ取得 */
        get: operations["getFeature"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** フィーチャ属性・ジオメトリ更新 */
        patch: operations["updateFeature"];
        trace?: never;
    };
    "/api/features/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** フィーチャ検索 (キーワード / 単一属性条件) */
        get: operations["searchFeatures"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/features/business-spatial-search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 業務エンティティ起点の空間検索 */
        post: operations["businessSpatialSearch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/features/condition-search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 条件検索プレビュー (保存は analysis-jobs の condition_search) */
        post: operations["conditionSearch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/features/{layerId}/{featureId}/business-links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** フィーチャに紐づく業務エンティティ */
        get: operations["getFeatureBusinessLinks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 土地一覧 */
        get: operations["listLands"];
        put?: never;
        /** 土地作成 */
        post: operations["createLand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lands/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 土地取得 */
        get: operations["getLand"];
        put?: never;
        post?: never;
        /** 土地削除 */
        delete: operations["deleteLand"];
        options?: never;
        head?: never;
        /** 土地更新 */
        patch: operations["updateLand"];
        trace?: never;
    };
    "/api/buildings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 建物一覧 */
        get: operations["listBuildings"];
        put?: never;
        /** 建物作成 */
        post: operations["createBuilding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/buildings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 建物取得 */
        get: operations["getBuilding"];
        put?: never;
        post?: never;
        /** 建物削除 */
        delete: operations["deleteBuilding"];
        options?: never;
        head?: never;
        /** 建物更新 */
        patch: operations["updateBuilding"];
        trace?: never;
    };
    "/api/parties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 関係者一覧 */
        get: operations["listParties"];
        put?: never;
        /** 関係者作成 */
        post: operations["createParty"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/parties/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 関係者取得 */
        get: operations["getParty"];
        put?: never;
        post?: never;
        /** 関係者削除 */
        delete: operations["deleteParty"];
        options?: never;
        head?: never;
        /** 関係者更新 */
        patch: operations["updateParty"];
        trace?: never;
    };
    "/api/party-relationships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 関係者リレーション作成 */
        post: operations["createPartyRelationship"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/party-relationships/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 関係者リレーション削除 */
        delete: operations["deletePartyRelationship"];
        options?: never;
        head?: never;
        /** 関係者リレーション更新 */
        patch: operations["updatePartyRelationship"];
        trace?: never;
    };
    "/api/zones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 区域一覧 */
        get: operations["listZones"];
        put?: never;
        /** 区域作成 */
        post: operations["createZone"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/zones/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 区域取得 */
        get: operations["getZone"];
        put?: never;
        post?: never;
        /** 区域削除 */
        delete: operations["deleteZone"];
        options?: never;
        head?: never;
        /** 区域更新 */
        patch: operations["updateZone"];
        trace?: never;
    };
    "/api/zones/{id}/party-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 区域の関係者サマリ */
        get: operations["getZonePartySummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/zone-layers/from-import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 取込レイヤから区域レイヤを生成 (バッファリング + 区域同期) */
        post: operations["createZoneLayerFromImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** GIS ファイル取込ジョブ作成 (worker-gis が GDAL で実行) */
        post: operations["createImportJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import-jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 取込ジョブ取得 */
        get: operations["getImportJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 分析ジョブ作成 (API 内の AnalysisJobRunner が実行) */
        post: operations["createAnalysisJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis-jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 分析ジョブ取得 */
        get: operations["getAnalysisJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tilejson/{layerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** レイヤの TileJSON */
        get: operations["getTileJson"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tiles/{layerId}/{z}/{x}/{y}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** MVT タイル (空タイルは 0 バイト) */
        get: operations["getTile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: string;
        };
        Project: {
            id: string;
            name: string;
            createdAt: string;
        };
        LayerAttribute: {
            name: string;
            dataType: string;
            ordinalPosition: number;
        };
        Layer: {
            id: string;
            projectId: string;
            name: string;
            schemaName: string;
            tableName: string;
            geometryColumn: string;
            geometryType: string;
            sourceSrid?: number | null;
            displaySrid: number;
            featureIdColumn: string;
            /** @description [west, south, east, north] (EPSG:4326) */
            bbox4326?: number[] | null;
            rowCount: number;
            isResult: boolean;
            /** @enum {string} */
            layerRole: "generic" | "zone";
            resultSetId?: string | null;
            resultSetName?: string | null;
            sourceLayerId?: string | null;
            tileSourceId: string;
            attributes?: components["schemas"]["LayerAttribute"][];
            createdAt: string;
        };
        Feature: {
            layerId: string;
            featureId: string;
            properties: {
                [key: string]: unknown;
            };
            /** @description GeoJSON geometry (EPSG:4326) */
            geometry?: unknown;
        };
        FeatureUpdateRequest: {
            properties?: {
                [key: string]: unknown;
            };
            /** @description GeoJSON geometry (EPSG:4326) */
            geometry?: unknown;
        };
        BusinessEntityLink: {
            id: string;
            label: string;
        };
        BusinessLinks: {
            lands: components["schemas"]["BusinessEntityLink"][];
            buildings: components["schemas"]["BusinessEntityLink"][];
        };
        FeatureSearchResult: {
            layerId: string;
            layerName: string;
            featureId: string;
            properties: {
                [key: string]: unknown;
            };
            /** @description GeoJSON geometry (EPSG:4326) */
            geometry?: unknown;
            matchSummary?: string | null;
            businessLinks?: components["schemas"]["BusinessLinks"];
            matchedBusinessLinks?: components["schemas"]["BusinessLinks"];
        };
        BusinessSpatialSearchRequest: {
            projectId?: string | null;
            targetLayerIds?: string[];
            sourceTypes?: ("land" | "building")[];
            businessQuery?: string | null;
            status?: string | null;
            landUse?: string | null;
            buildingUse?: string | null;
            partyQuery?: string | null;
            partyType?: string | null;
            relationType?: string | null;
            /** @description intersects | contains | within | dwithin */
            spatialOperator?: string | null;
            distanceMeters?: number | null;
            /** @default 100 */
            limit: number;
        };
        ConditionQueryCondition: {
            /** @enum {string} */
            type: "attribute" | "spatial" | "business";
            layerId?: string | null;
            field?: string | null;
            /** @description attribute: =, !=, <, <=, >, >=, LIKE, IN, IS NULL */
            operator?: string | null;
            value?: unknown;
            values?: string[] | null;
            /** @description layer | business */
            comparisonTarget?: string | null;
            sourceTypes?: ("land" | "building")[] | null;
            businessQuery?: string | null;
            status?: string | null;
            landUse?: string | null;
            buildingUse?: string | null;
            partyQuery?: string | null;
            partyType?: string | null;
            relationType?: string | null;
            /** @description intersects | contains | within | dwithin */
            spatialOperator?: string | null;
            distanceMeters?: number | null;
        };
        ConditionQuery: {
            projectId?: string | null;
            targetLayerIds: string[];
            keyword?: string | null;
            conditions?: components["schemas"]["ConditionQueryCondition"][];
            /** @default 100 */
            limit: number;
        };
        PartyRelationship: {
            id: string;
            projectId: string;
            partyId: string;
            partyName?: string | null;
            /** @enum {string} */
            targetType: "land" | "building";
            targetId: string;
            targetLabel?: string | null;
            relationType: string;
            note?: string | null;
        };
        /** @description 作成時は partyId / targetType / targetId / relationType が必要。更新は差分のみ */
        PartyRelationshipWriteRequest: {
            projectId?: string;
            partyId?: string;
            /** @enum {string} */
            targetType?: "land" | "building";
            targetId?: string;
            relationType?: string;
            note?: string | null;
        } & {
            [key: string]: unknown;
        };
        Land: {
            id: string;
            projectId: string;
            lotNumber: string;
            address: string;
            landUse?: string | null;
            areaSqm?: number | null;
            registeredOwner?: string | null;
            rightType?: string | null;
            registrationCause?: string | null;
            registrationAcceptedOn?: string | null;
            status: string;
            memo?: string | null;
            sourceLayerId?: string | null;
            sourceFeatureId?: string | null;
            buildings?: components["schemas"]["BusinessEntityLink"][];
            relationships?: components["schemas"]["PartyRelationship"][];
        };
        /** @description 作成時は lotNumber / address が必要。更新は差分のみ */
        LandWriteRequest: {
            id?: string;
            projectId?: string;
            lotNumber?: string;
            address?: string;
            landUse?: string | null;
            areaSqm?: number | null;
            registeredOwner?: string | null;
            rightType?: string | null;
            registrationCause?: string | null;
            registrationAcceptedOn?: string | null;
            status?: string;
            memo?: string | null;
            sourceLayerId?: string | null;
            sourceFeatureId?: string | null;
        } & {
            [key: string]: unknown;
        };
        Building: {
            id: string;
            projectId: string;
            landId?: string | null;
            landLabel?: string | null;
            name: string;
            buildingLocation?: string | null;
            houseNumber?: string | null;
            buildingUse?: string | null;
            floors?: number | null;
            totalFloorAreaSqm?: number | null;
            structure?: string | null;
            registeredOwner?: string | null;
            rightType?: string | null;
            registrationAcceptedOn?: string | null;
            status: string;
            memo?: string | null;
            sourceLayerId?: string | null;
            sourceFeatureId?: string | null;
            relationships?: components["schemas"]["PartyRelationship"][];
        };
        /** @description 作成時は name が必要。更新は差分のみ */
        BuildingWriteRequest: {
            id?: string;
            projectId?: string;
            landId?: string | null;
            name?: string;
            buildingLocation?: string | null;
            houseNumber?: string | null;
            buildingUse?: string | null;
            floors?: number | null;
            totalFloorAreaSqm?: number | null;
            structure?: string | null;
            registeredOwner?: string | null;
            rightType?: string | null;
            registrationAcceptedOn?: string | null;
            status?: string;
            memo?: string | null;
            sourceLayerId?: string | null;
            sourceFeatureId?: string | null;
        } & {
            [key: string]: unknown;
        };
        Party: {
            id: string;
            projectId: string;
            name: string;
            partyType: string;
            contact?: string | null;
            address?: string | null;
            memo?: string | null;
            tags?: string[];
            relationships?: components["schemas"]["PartyRelationship"][];
        };
        /** @description 作成時は name / partyType が必要。更新は差分のみ */
        PartyWriteRequest: {
            id?: string;
            projectId?: string;
            name?: string;
            partyType?: string;
            contact?: string | null;
            address?: string | null;
            memo?: string | null;
            tags?: string[];
        } & {
            [key: string]: unknown;
        };
        Zone: {
            id: string;
            projectId: string;
            name: string;
            zoneType?: string | null;
            status: string;
            memo?: string | null;
            zoneLayerId: string;
            zoneFeatureId: string;
            sourceLayerId: string;
            sourceFeatureId: string;
            landCount?: number;
            buildingCount?: number;
            lands?: components["schemas"]["BusinessEntityLink"][];
            buildings?: components["schemas"]["BusinessEntityLink"][];
        };
        /** @description 作成時は name と区域フィーチャ参照が必要。更新は差分のみ */
        ZoneWriteRequest: {
            id?: string;
            projectId?: string;
            name?: string;
            zoneType?: string | null;
            status?: string;
            memo?: string | null;
            zoneLayerId?: string;
            zoneFeatureId?: string;
            sourceLayerId?: string;
            sourceFeatureId?: string;
        } & {
            [key: string]: unknown;
        };
        ZonePartyBreakdown: {
            key: string;
            count: number;
        };
        ZonePartySummaryEntry: {
            id: string;
            name: string;
            partyType: string;
            tags?: string[];
            zoneInvolvement: number;
            projectInvolvement: number;
            relationTypes?: string[];
            coverageRatio: number;
        };
        ZonePartySummary: {
            zoneId: string;
            containedCount: number;
            partyCount: number;
            typeBreakdown?: components["schemas"]["ZonePartyBreakdown"][];
            tagBreakdown?: components["schemas"]["ZonePartyBreakdown"][];
            parties?: components["schemas"]["ZonePartySummaryEntry"][];
        };
        ZoneLayerFromImportRequest: {
            projectId?: string | null;
            layerId: string;
            name?: string | null;
            zoneType?: string | null;
            status?: string | null;
            nameField?: string | null;
        };
        ZoneLayerOperation: {
            layer: components["schemas"]["Layer"];
            zonesCreated: number;
            zonesUpdated: number;
            zones?: components["schemas"]["Zone"][];
        };
        ImportJob: {
            id: string;
            projectId: string;
            filename: string;
            /** @enum {string} */
            format: "shapefile" | "geojson" | "gml" | "kml" | "gpx";
            sourceSrid?: number | null;
            /** @enum {string} */
            status: "pending" | "running" | "succeeded" | "failed";
            errorMessage?: string | null;
            layerId?: string | null;
            /** @enum {string} */
            layerRole: "generic" | "zone";
            createdAt: string;
            startedAt?: string | null;
            finishedAt?: string | null;
        };
        AnalysisJobRequest: {
            projectId?: string | null;
            name?: string | null;
            /** @description operation=and_filter (旧形式) の対象レイヤ */
            targetLayerId?: string | null;
            /** @description and_filter | condition_search */
            operation?: string | null;
            attributeConditions?: {
                layerId: string;
                field: string;
                operator: string;
                value?: unknown;
                values?: string[] | null;
            }[];
            spatialConditions?: {
                layerId: string;
                /** @enum {string} */
                operator: "intersects" | "contains" | "within" | "dwithin";
                distanceMeters?: number | null;
            }[];
            conditionQuery?: components["schemas"]["ConditionQuery"];
        };
        AnalysisJob: {
            id: string;
            projectId: string;
            name: string;
            criteria: {
                [key: string]: unknown;
            };
            /** @enum {string} */
            status: "pending" | "running" | "succeeded" | "failed";
            errorMessage?: string | null;
            resultLayerId?: string | null;
            resultSetId?: string | null;
            resultCount?: number | null;
            createdAt: string;
            startedAt?: string | null;
            finishedAt?: string | null;
        };
        VectorLayer: {
            id: string;
            fields: {
                [key: string]: string;
            };
        };
        TileJson: {
            tilejson: string;
            name: string;
            tiles: string[];
            vector_layers: components["schemas"]["VectorLayer"][];
            bounds?: number[] | null;
            minzoom?: number;
            maxzoom?: number;
        };
    };
    responses: {
        /** @description リクエスト不正 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 対象が存在しない */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        PathId: string;
        /** @description 1 ページの最大件数 */
        ListLimit: number;
        /** @description 読み飛ばす件数 */
        ListOffset: number;
        PathFeatureId: string;
    };
    requestBodies: never;
    headers: {
        /** @description フィルタ適用後の総件数 (limit/offset 適用前) */
        XTotalCount: number;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status: string;
                    };
                };
            };
        };
    };
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
        };
    };
    listLayers: {
        parameters: {
            query?: {
                projectId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Layer"][];
                };
            };
        };
    };
    deleteLayer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 削除済み */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    listLayerAttributeValues: {
        parameters: {
            query: {
                field: string;
                limit?: number;
            };
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    deleteResultSet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 削除済み */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    getFeature: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
                featureId: components["parameters"]["PathFeatureId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feature"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateFeature: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
                featureId: components["parameters"]["PathFeatureId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeatureUpdateRequest"];
            };
        };
        responses: {
            /** @description 更新後のフィーチャ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feature"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    searchFeatures: {
        parameters: {
            query?: {
                projectId?: string;
                layerId?: string;
                q?: string;
                field?: string;
                operator?: string;
                value?: string;
                linkedOnly?: boolean;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureSearchResult"][];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    businessSpatialSearch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BusinessSpatialSearchRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureSearchResult"][];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    conditionSearch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConditionQuery"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureSearchResult"][];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getFeatureBusinessLinks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                layerId: string;
                featureId: components["parameters"]["PathFeatureId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusinessLinks"];
                };
            };
        };
    };
    listLands: {
        parameters: {
            query?: {
                projectId?: string;
                q?: string;
                status?: string;
                landUse?: string;
                partyType?: string;
                relationType?: string;
                linkedOnly?: boolean;
                sourceLayerId?: string;
                /** @description west,south,east,north (EPSG:4326) */
                bbox?: string;
                intersectsLayerId?: string;
                intersectsFeatureId?: string;
                distanceMeters?: number;
                /** @description 1 ページの最大件数 */
                limit?: components["parameters"]["ListLimit"];
                /** @description 読み飛ばす件数 */
                offset?: components["parameters"]["ListOffset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "X-Total-Count": components["headers"]["XTotalCount"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Land"][];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    createLand: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LandWriteRequest"];
            };
        };
        responses: {
            /** @description 作成済み */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Land"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getLand: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Land"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteLand: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 削除済み */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateLand: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LandWriteRequest"];
            };
        };
        responses: {
            /** @description 更新後 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Land"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    listBuildings: {
        parameters: {
            query?: {
                projectId?: string;
                q?: string;
                landId?: string;
                status?: string;
                buildingUse?: string;
                partyType?: string;
                relationType?: string;
                linkedOnly?: boolean;
                sourceLayerId?: string;
                bbox?: string;
                intersectsLayerId?: string;
                intersectsFeatureId?: string;
                distanceMeters?: number;
                /** @description 1 ページの最大件数 */
                limit?: components["parameters"]["ListLimit"];
                /** @description 読み飛ばす件数 */
                offset?: components["parameters"]["ListOffset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "X-Total-Count": components["headers"]["XTotalCount"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Building"][];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    createBuilding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuildingWriteRequest"];
            };
        };
        responses: {
            /** @description 作成済み */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Building"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getBuilding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Building"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteBuilding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 削除済み */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateBuilding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuildingWriteRequest"];
            };
        };
        responses: {
            /** @description 更新後 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Building"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    listParties: {
        parameters: {
            query?: {
                projectId?: string;
                q?: string;
                partyType?: string;
                relationType?: string;
                linkedOnly?: boolean;
                targetType?: "land" | "building";
                /** @description 1 ページの最大件数 */
                limit?: components["parameters"]["ListLimit"];
                /** @description 読み飛ばす件数 */
                offset?: components["parameters"]["ListOffset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "X-Total-Count": components["headers"]["XTotalCount"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Party"][];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    createParty: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PartyWriteRequest"];
            };
        };
        responses: {
            /** @description 作成済み */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Party"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getParty: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Party"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteParty: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 削除済み */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateParty: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PartyWriteRequest"];
            };
        };
        responses: {
            /** @description 更新後 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Party"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    createPartyRelationship: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PartyRelationshipWriteRequest"];
            };
        };
        responses: {
            /** @description 作成済み */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartyRelationship"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    deletePartyRelationship: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 削除済み */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    updatePartyRelationship: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PartyRelationshipWriteRequest"];
            };
        };
        responses: {
            /** @description 更新後 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartyRelationship"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    listZones: {
        parameters: {
            query?: {
                projectId?: string;
                q?: string;
                status?: string;
                zoneType?: string;
                linkedOnly?: boolean;
                zoneLayerId?: string;
                sourceLayerId?: string;
                /** @description 1 ページの最大件数 */
                limit?: components["parameters"]["ListLimit"];
                /** @description 読み飛ばす件数 */
                offset?: components["parameters"]["ListOffset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "X-Total-Count": components["headers"]["XTotalCount"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Zone"][];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    createZone: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ZoneWriteRequest"];
            };
        };
        responses: {
            /** @description 作成済み */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Zone"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getZone: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Zone"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteZone: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 削除済み */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateZone: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ZoneWriteRequest"];
            };
        };
        responses: {
            /** @description 更新後 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Zone"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    getZonePartySummary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZonePartySummary"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    createZoneLayerFromImport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ZoneLayerFromImportRequest"];
            };
        };
        responses: {
            /** @description 作成済み */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZoneLayerOperation"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    createImportJob: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    projectId?: string;
                    /** @enum {string} */
                    format?: "shapefile" | "geojson" | "gml" | "kml" | "gpx";
                    sourceSrid?: number;
                    /** @enum {string} */
                    layerRole?: "generic" | "zone";
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description 受付済み */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportJob"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getImportJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportJob"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    createAnalysisJob: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisJobRequest"];
            };
        };
        responses: {
            /** @description 受付済み */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisJob"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getAnalysisJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisJob"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getTileJson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                layerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TileJson"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getTile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                layerId: string;
                z: number;
                x: number;
                y: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.mapbox-vector-tile": string;
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
}
