/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getFeedbackCapabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getFeedbackMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{applicationKey}/manifest": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationKey: components["parameters"]["ApplicationKey"];
            };
            cookie?: never;
        };
        get: operations["getFeedbackApplicationManifest"];
        put: operations["putFeedbackApplicationManifest"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review-context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getFeedbackReviewContext"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listFeedbackSessions"];
        put?: never;
        post: operations["createFeedbackSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get: operations["getFeedbackSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["patchFeedbackSession"];
        trace?: never;
    };
    "/sessions/{sessionId}/threads": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get: operations["listFeedbackThreads"];
        put?: never;
        post: operations["createFeedbackThread"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/threads/{threadId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                threadId: components["parameters"]["ThreadId"];
            };
            cookie?: never;
        };
        get: operations["getFeedbackThread"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/threads/{threadId}/deep-link": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                threadId: components["parameters"]["ThreadId"];
            };
            cookie?: never;
        };
        get: operations["getFeedbackThreadDeepLink"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/threads/{threadId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                threadId: components["parameters"]["ThreadId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createFeedbackMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages/{messageId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                messageId: components["parameters"]["MessageId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["patchFeedbackMessage"];
        trace?: never;
    };
    "/messages/{messageId}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                messageId: components["parameters"]["MessageId"];
            };
            cookie?: never;
        };
        get: operations["listFeedbackMessageVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/threads/{threadId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                threadId: components["parameters"]["ThreadId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["patchFeedbackThreadStatus"];
        trace?: never;
    };
    "/threads/{threadId}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                threadId: components["parameters"]["ThreadId"];
            };
            cookie?: never;
        };
        get: operations["getFeedbackEvidence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createFeedbackExport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exports/{exportId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exportId: components["parameters"]["ExportId"];
            };
            cookie?: never;
        };
        get: operations["getFeedbackExport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exports/{exportId}/download": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exportId: components["parameters"]["ExportId"];
            };
            cookie?: never;
        };
        get: operations["downloadFeedbackExport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/backup-policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getFeedbackBackupPolicy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["patchFeedbackBackupPolicy"];
        trace?: never;
    };
    "/backups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listFeedbackBackups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/backups/{backupId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                backupId: components["parameters"]["BackupId"];
            };
            cookie?: never;
        };
        get: operations["getFeedbackBackup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/backups/{backupId}/download": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                backupId: components["parameters"]["BackupId"];
            };
            cookie?: never;
        };
        get: operations["downloadFeedbackBackup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/backups/{backupId}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                backupId: components["parameters"]["BackupId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["retryFeedbackBackup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/retention-policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getFeedbackRetentionPolicy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["patchFeedbackRetentionPolicy"];
        trace?: never;
    };
    "/notification-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @deprecated */
        get: operations["getFeedbackNotificationSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @deprecated */
        patch: operations["patchFeedbackNotificationSettings"];
        trace?: never;
    };
    "/connector-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listFeedbackConnectorTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notification-connectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listFeedbackNotificationConnectors"];
        put?: never;
        post: operations["createFeedbackNotificationConnector"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notification-connectors/{connectorId}": {
        parameters: {
            query: {
                applicationKey: components["parameters"]["ApplicationKeyQuery"];
                externalWorkspaceKey: components["parameters"]["ExternalWorkspaceKeyQuery"];
            };
            header: {
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                connectorId: components["parameters"]["ConnectorId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteFeedbackNotificationConnector"];
        options?: never;
        head?: never;
        patch: operations["patchFeedbackNotificationConnector"];
        trace?: never;
    };
    "/memberships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listFeedbackWorkspaceMemberships"];
        put?: never;
        post: operations["createFeedbackWorkspaceMembership"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memberships/{userId}": {
        parameters: {
            query: {
                applicationKey: components["parameters"]["ApplicationKeyQuery"];
                externalWorkspaceKey: components["parameters"]["ExternalWorkspaceKeyQuery"];
            };
            header: {
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteFeedbackWorkspaceMembership"];
        options?: never;
        head?: never;
        patch: operations["patchFeedbackWorkspaceMembership"];
        trace?: never;
    };
    "/notification-deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listFeedbackNotificationDeliveries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notification-deliveries/{deliveryId}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deliveryId: components["parameters"]["DeliveryId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["retryFeedbackNotificationDelivery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        FeedbackApplicationManifestV1: components["schemas"]["application-manifest.schema"];
        FeedbackLocationV1: components["schemas"]["location.schema"];
        FeedbackTargetV1: components["schemas"]["target.schema"];
        FeedbackWebhookEventV1: components["schemas"]["webhook-event.schema"];
        FeedbackConnectorProtocolV1: components["schemas"]["connector-protocol.schema"];
        FeedbackCapabilities: {
            /** @constant */
            apiVersion: "1.0";
            /** @constant */
            apiMajorVersion: 1;
            manifestSchemaVersions: "1"[];
            targetSchemaVersions: "1"[];
            evidence: {
                maxBytes: number;
                maxCountPerWorkspace: number;
                acceptedContentTypes: ("image/png" | "image/webp")[];
            };
            features: string[];
        };
        FeedbackProblem: {
            /** Format: uri-reference */
            type: string;
            title: string;
            status: number;
            detail?: string;
            code: string;
            requestId: string;
        };
        /** @enum {unknown} */
        FeedbackPermission: "feedback.read" | "feedback.comment" | "feedback.manage" | "feedback.admin";
        FeedbackParticipant: {
            principalId: string;
            displayName?: string | null;
            participantName?: string | null;
        };
        FeedbackMembership: {
            applicationKey: string;
            externalWorkspaceKey: string;
            permissions: components["schemas"]["FeedbackPermission"][];
        };
        FeedbackMe: {
            participant: components["schemas"]["FeedbackParticipant"];
            memberships: components["schemas"]["FeedbackMembership"][];
        };
        FeedbackWorkspaceMember: {
            /** Format: uuid */
            userId: string;
            issuer: string;
            subject: string;
            email?: string | null;
            displayName?: string | null;
            permissions: components["schemas"]["FeedbackPermission"][];
            version: number;
        };
        FeedbackMembershipCreateRequest: {
            issuer: string;
            subject: string;
            permissions: components["schemas"]["FeedbackPermission"][];
        };
        FeedbackMembershipPatchRequest: {
            permissions: components["schemas"]["FeedbackPermission"][];
        };
        FeedbackHostContextV1: {
            /** @constant */
            schemaVersion: "1";
            applicationKey: string;
            environmentKey: string;
            externalWorkspaceKey: string;
            release: string;
            locale?: string;
        };
        FeedbackParticipantPolicy: {
            /** @constant */
            mode: "authenticated-identity";
        } | {
            /** @enum {unknown} */
            mode: "prompt" | "authenticated-and-prompt";
            /** @enum {unknown} */
            storage: "memory" | "local-storage" | "host";
        };
        FeedbackEvidencePolicy: {
            enabled: boolean;
            maxBytes: number;
            acceptedContentTypes: ("image/png" | "image/webp")[];
        };
        FeedbackReviewContextV1: {
            session: components["schemas"]["FeedbackSessionV1"] | null;
            /** @enum {unknown} */
            scope: "reviewable" | "excluded" | "unregistered";
            /** @enum {unknown} */
            posting: "allow" | "warn" | "deny";
            permissions: components["schemas"]["FeedbackPermission"][];
            participantPolicy: components["schemas"]["FeedbackParticipantPolicy"];
            evidencePolicy: components["schemas"]["FeedbackEvidencePolicy"];
        };
        /** @enum {string} */
        FeedbackSessionStatus: "draft" | "open" | "closed";
        FeedbackSessionV1: {
            /** Format: uuid */
            id: string;
            applicationKey: string;
            environmentKey: string;
            externalWorkspaceKey: string;
            manifestVersion: string;
            title: string;
            description?: string | null;
            status: components["schemas"]["FeedbackSessionStatus"];
            /** @enum {unknown} */
            outOfScopePosting: "allow" | "warn" | "deny";
            /** Format: date-time */
            startAt?: string | null;
            /** Format: date-time */
            endAt?: string | null;
            scopes: components["schemas"]["FeedbackSessionScopeV1"][];
            perspectives: components["schemas"]["FeedbackSessionPerspectiveV1"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            version: number;
        };
        FeedbackSessionScopeV1: {
            pageKey: string;
            routeTemplate?: string | null;
            reviewable: boolean;
            /** @description この画面で確認する観点コード。空配列または省略時は有効な観点すべて。 */
            perspectiveCodes?: string[];
        };
        FeedbackSessionPerspectiveV1: {
            code: string;
            label: string;
            /** @enum {unknown} */
            status: "active" | "future" | "out-of-scope";
            guidance?: string | null;
        };
        FeedbackSessionPage: {
            items: components["schemas"]["FeedbackSessionV1"][];
            nextCursor?: string | null;
            totalCount?: number;
        };
        FeedbackSessionCreateRequest: {
            applicationKey: string;
            environmentKey: string;
            externalWorkspaceKey: string;
            manifestVersion: string;
            title: string;
            description?: string | null;
            /** @default draft */
            status: components["schemas"]["FeedbackSessionStatus"];
            /**
             * @default warn
             * @enum {unknown}
             */
            outOfScopePosting: "allow" | "warn" | "deny";
            /** Format: date-time */
            startAt?: string | null;
            /** Format: date-time */
            endAt?: string | null;
            scopes?: components["schemas"]["FeedbackSessionScopeV1"][];
            perspectives?: components["schemas"]["FeedbackSessionPerspectiveV1"][];
        };
        FeedbackSessionPatchRequest: {
            title?: string;
            description?: string | null;
            status?: components["schemas"]["FeedbackSessionStatus"];
            /** @enum {unknown} */
            outOfScopePosting?: "allow" | "warn" | "deny";
            /** Format: date-time */
            startAt?: string | null;
            /** Format: date-time */
            endAt?: string | null;
            scopes?: components["schemas"]["FeedbackSessionScopeV1"][];
            perspectives?: components["schemas"]["FeedbackSessionPerspectiveV1"][];
        };
        /** @enum {string} */
        FeedbackThreadStatus: "open" | "resolved";
        FeedbackMessageV1: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            threadId: string;
            author: components["schemas"]["FeedbackParticipant"];
            body: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            editedAt?: string | null;
            version: number;
        };
        FeedbackMessageVersionV1: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            threadId: string;
            author: components["schemas"]["FeedbackParticipant"];
            body: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            editedAt?: string | null;
            version: number;
            current: boolean;
        };
        FeedbackThreadV1: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            sessionId: string;
            displayNumber: number;
            location: components["schemas"]["location.schema"];
            target: components["schemas"]["target.schema"];
            perspectiveCode: string;
            status: components["schemas"]["FeedbackThreadStatus"];
            reporter: components["schemas"]["FeedbackParticipant"];
            /** @default false */
            evidenceAvailable: boolean;
            messages: components["schemas"]["FeedbackMessageV1"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            version: number;
        };
        FeedbackThreadPage: {
            items: components["schemas"]["FeedbackThreadV1"][];
            nextCursor?: string | null;
            totalCount?: number;
        };
        FeedbackDeepLink: {
            /** Format: uri */
            url: string;
        };
        FeedbackThreadCreateRequest: {
            location: components["schemas"]["location.schema"];
            target: components["schemas"]["target.schema"];
            perspectiveCode: string;
            body: string;
            participantName?: string | null;
            evidence?: {
                /** @enum {unknown} */
                contentType: "image/png" | "image/webp";
                dataBase64: string;
                viewportWidth: number;
                viewportHeight: number;
                pixelRatio: number;
                /** Format: date-time */
                capturedAt: string;
            } | null;
        };
        FeedbackMessageCreateRequest: {
            body: string;
            participantName?: string | null;
        };
        FeedbackMessagePatchRequest: {
            body: string;
            participantName?: string | null;
        };
        FeedbackExportRequest: {
            applicationKey: string;
            environmentKey: string;
            externalWorkspaceKey: string;
            /** Format: uuid */
            sessionId?: string | null;
            /** @enum {unknown} */
            format: "csv" | "xlsx";
            /** @default ja-JP */
            locale: string;
            /** @default Asia/Tokyo */
            timezone: string;
        };
        FeedbackExportJob: {
            /** Format: uuid */
            id: string;
            /** @enum {unknown} */
            status: "queued" | "running" | "completed" | "failed";
            /** Format: uri-reference */
            downloadUrl?: string | null;
            /** Format: date-time */
            expiresAt?: string | null;
            /** Format: date-time */
            createdAt: string;
            error?: string | null;
        };
        FeedbackBackupPolicy: {
            /** @default false */
            enabled: boolean;
            /** @default Asia/Tokyo */
            timezone: string;
            /** @default 02:00 */
            fullBackupAt: string;
            /** @default 60 */
            incrementalIntervalMinutes: number;
            /** @default true */
            includeEvidence: boolean;
            retentionDays: number | null;
        };
        FeedbackBackupPolicyView: {
            policy: components["schemas"]["FeedbackBackupPolicy"];
            /** Format: date-time */
            nextExecutionAt: string | null;
            /** Format: date-time */
            nextFullAt: string | null;
            /** Format: date-time */
            nextIncrementalAt: string | null;
            /** Format: date-time */
            lastSuccessfulAt: string | null;
            changeCursor: number;
            auditCursor: number;
        };
        FeedbackBackupRun: {
            /** Format: uuid */
            id: string;
            /** @enum {unknown} */
            kind: "full" | "incremental";
            /** @enum {unknown} */
            status: "queued" | "running" | "completed" | "failed" | "superseded";
            /** Format: date-time */
            scheduledFor: string;
            /** Format: uri-reference */
            downloadUrl?: string | null;
            fromChangeSequence: number;
            toChangeSequence?: number | null;
            fromAuditSequence: number;
            toAuditSequence?: number | null;
            archiveSha256?: string | null;
            archiveBytes?: number | null;
            entryCounts?: {
                [key: string]: number;
            } | null;
            /** Format: date-time */
            historyCoverageStartedAt: string;
            /** Format: date-time */
            expiresAt?: string | null;
            /** Format: date-time */
            completedAt?: string | null;
            /** Format: date-time */
            createdAt: string;
            error?: string | null;
        };
        FeedbackBackupRunPage: {
            items: components["schemas"]["FeedbackBackupRun"][];
            nextCursor: string | null;
        };
        FeedbackConnectorType: {
            key: string;
            displayName: string;
            /** @constant */
            protocolVersion: "1";
            supportedEvents: string[];
            enabled: boolean;
            /** @enum {unknown} */
            healthStatus: "unknown" | "healthy" | "unhealthy";
            /** Format: date-time */
            healthCheckedAt: string | null;
            healthError: string | null;
        };
        FeedbackNotificationConnectorCreateRequest: {
            connectorType: string;
            name: string;
            destinationRef: string;
            /** @default true */
            enabled: boolean;
            /** @default false */
            includeBody: boolean;
        };
        FeedbackNotificationConnectorPatchRequest: {
            name: string;
            destinationRef: string;
            enabled: boolean;
            includeBody: boolean;
        };
        FeedbackNotificationConnector: {
            /** Format: uuid */
            id: string;
            connectorType: string;
            displayName: string;
            name: string;
            destinationRef: string;
            enabled: boolean;
            includeBody: boolean;
            /** @enum {unknown} */
            healthStatus: "unknown" | "healthy" | "unhealthy";
            /** Format: date-time */
            healthCheckedAt: string | null;
            healthError: string | null;
            version: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        FeedbackRetentionPolicy: {
            evidenceRetentionDays: number | null;
            /** @default 7 */
            exportRetentionDays: number;
        };
        FeedbackNotificationSettings: {
            webhookEnabled: boolean;
            /** Format: uri */
            webhookEndpoint?: string | null;
            /** @default false */
            includeBody: boolean;
            /** @default false */
            includeEvidence: boolean;
        };
        FeedbackNotificationAttempt: {
            retryCycle: number;
            attempt: number;
            /** @enum {unknown} */
            status: "delivered" | "failed";
            responseStatus?: number | null;
            error?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        FeedbackNotificationDelivery: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            connectorId?: string | null;
            connectorName?: string | null;
            eventType: string;
            /** @enum {unknown} */
            status: "pending" | "processing" | "delivered" | "failed";
            retryCycle: number;
            attemptCount: number;
            /** Format: date-time */
            availableAt: string;
            /** Format: date-time */
            deliveredAt?: string | null;
            lastError?: string | null;
            /** Format: date-time */
            createdAt: string;
            attempts: components["schemas"]["FeedbackNotificationAttempt"][];
        };
        /** FeedbackApplicationManifestV1 */
        "application-manifest.schema": {
            /** @constant */
            schemaVersion: "1";
            applicationKey: string;
            displayName: string;
            manifestVersion: string;
            routes: {
                pageKey: string;
                template: string;
                label: string;
                group?: string;
                parameters?: {
                    [key: string]: {
                        /** @enum {unknown} */
                        persistence: "store" | "hash" | "discard";
                    };
                };
                queryParameters?: {
                    [key: string]: {
                        /** @enum {unknown} */
                        persistence: "store" | "hash" | "discard";
                    };
                };
                aliases?: string[];
            }[];
        };
        /** FeedbackLocationV1 */
        "location.schema": {
            /** @constant */
            schemaVersion: "1";
            pageKey: string;
            routeTemplate: string;
            pathParameters: {
                [key: string]: string;
            };
            queryParameters?: {
                [key: string]: string;
            };
        };
        /** FeedbackTargetV1 */
        "target.schema": {
            /** @constant */
            schemaVersion: "1";
            /** @constant */
            kind: "ui-element";
            elementKey: string;
            relativeX: number;
            relativeY: number;
        } | {
            /** @constant */
            schemaVersion: "1";
            /** @constant */
            kind: "screen-position";
            relativeX: number;
            relativeY: number;
        } | {
            /** @constant */
            schemaVersion: "1";
            /** @constant */
            kind: "map-feature";
            /** @constant */
            provider: "maplibre";
            sourceKey: string;
            sourceLayer?: string;
            featureKey: string;
            longitude: number;
            latitude: number;
        } | {
            /** @constant */
            schemaVersion: "1";
            /** @constant */
            kind: "map-position";
            longitude: number;
            latitude: number;
        };
        /** FeedbackWebhookEventV1 */
        "webhook-event.schema": {
            /** @constant */
            schemaVersion: "1";
            /** Format: uuid */
            eventId: string;
            requestId: string;
            /** @enum {unknown} */
            eventType: "feedback.thread.created.v1" | "feedback.message.created.v1" | "feedback.thread.resolved.v1" | "feedback.thread.reopened.v1";
            /** Format: date-time */
            occurredAt: string;
            tenantKey: string;
            applicationKey: string;
            environmentKey: string;
            externalWorkspaceKey: string;
            /** Format: uuid */
            sessionId: string;
            /** Format: uuid */
            threadId: string;
            actor: {
                principalId: string;
                displayName?: string | null;
                participantName?: string | null;
            };
            /** Format: uri */
            deepLink: string;
            body?: string;
            /** Format: uri-reference */
            evidenceUrl?: string;
        };
        /** @constant */
        protocolVersion: "1";
        compatibleProtocolVersions: string[];
        manifest: {
            /** @constant */
            kind: "manifest";
            protocolVersion: components["schemas"]["protocolVersion"];
            compatibleProtocolVersions: components["schemas"]["compatibleProtocolVersions"];
            connectorKey: string;
            displayName: string;
            supportedEvents: ("feedback.thread.created.v1" | "feedback.message.created.v1" | "feedback.thread.resolved.v1" | "feedback.thread.reopened.v1")[];
            /** Format: uri-reference */
            healthPath: string;
        };
        deliveryRequest: {
            /** @constant */
            kind: "delivery-request";
            protocolVersion: components["schemas"]["protocolVersion"];
            /** Format: uuid */
            deliveryId: string;
            /** Format: uuid */
            eventId: string;
            destinationRef: string;
            /** Format: date-time */
            occurredAt: string;
            event: components["schemas"]["webhook-event.schema"] & unknown;
        };
        deliveryResult: {
            /** @constant */
            kind: "delivery-result";
            protocolVersion: components["schemas"]["protocolVersion"];
            /** Format: uuid */
            deliveryId: string;
            /** @enum {unknown} */
            status: "accepted" | "duplicate";
            /** Format: date-time */
            receivedAt: string;
        };
        /** FeedbackConnectorProtocolV1 */
        "connector-protocol.schema": {
            $defs: {
                /** @constant */
                protocolVersion: "1";
                compatibleProtocolVersions: string[];
                manifest: {
                    /** @constant */
                    kind: "manifest";
                    protocolVersion: components["schemas"]["protocolVersion"];
                    compatibleProtocolVersions: components["schemas"]["compatibleProtocolVersions"];
                    connectorKey: string;
                    displayName: string;
                    supportedEvents: ("feedback.thread.created.v1" | "feedback.message.created.v1" | "feedback.thread.resolved.v1" | "feedback.thread.reopened.v1")[];
                    /** Format: uri-reference */
                    healthPath: string;
                };
                deliveryRequest: {
                    /** @constant */
                    kind: "delivery-request";
                    protocolVersion: components["schemas"]["protocolVersion"];
                    /** Format: uuid */
                    deliveryId: string;
                    /** Format: uuid */
                    eventId: string;
                    destinationRef: string;
                    /** Format: date-time */
                    occurredAt: string;
                    event: components["schemas"]["webhook-event.schema"] & unknown;
                };
                deliveryResult: {
                    /** @constant */
                    kind: "delivery-result";
                    protocolVersion: components["schemas"]["protocolVersion"];
                    /** Format: uuid */
                    deliveryId: string;
                    /** @enum {unknown} */
                    status: "accepted" | "duplicate";
                    /** Format: date-time */
                    receivedAt: string;
                };
            };
        } & (components["schemas"]["manifest"] | components["schemas"]["deliveryRequest"] | components["schemas"]["deliveryResult"]);
    };
    responses: {
        /** @description 契約または manifest に適合しない入力 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["FeedbackProblem"];
            };
        };
        /** @description 未認証または token 無効 */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["FeedbackProblem"];
            };
        };
        /** @description feedback permission 不足 */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["FeedbackProblem"];
            };
        };
        /** @description resource 不在または存在秘匿 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["FeedbackProblem"];
            };
        };
        /** @description open session 競合などの一意制約違反 */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["FeedbackProblem"];
            };
        };
        /** @description ETag が古い */
        PreconditionFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["FeedbackProblem"];
            };
        };
        /** @description evidence または request が上限を超えた */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["FeedbackProblem"];
            };
        };
        /** @description rate limit または quota 超過 */
        TooManyRequests: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["FeedbackProblem"];
            };
        };
        /** @description DB または必須依存が利用不能 */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["FeedbackProblem"];
            };
        };
        /** @description evidence size の範囲外または複数 byte range */
        RangeNotSatisfiable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["FeedbackProblem"];
            };
        };
    };
    parameters: {
        ApplicationKey: string;
        ApplicationKeyQuery: string;
        EnvironmentKeyQuery: string;
        ExternalWorkspaceKeyQuery: string;
        SessionId: string;
        ThreadId: string;
        MessageId: string;
        ExportId: string;
        BackupId: string;
        ConnectorId: string;
        UserId: string;
        DeliveryId: string;
        Cursor: string;
        Limit: number;
        IdempotencyKey: string;
        IfMatch: string;
        IfMatchOptional: string;
        Range: string;
    };
    requestBodies: never;
    headers: {
        /** @description resource version。更新時は If-Match へそのまま指定する。 */
        ETag: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getFeedbackCapabilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API と schema の対応能力 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackCapabilities"];
                };
            };
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getFeedbackMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 認証主体と workspace 権限 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackMe"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getFeedbackApplicationManifest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationKey: components["parameters"]["ApplicationKey"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 登録済み application manifest */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["application-manifest.schema"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    putFeedbackApplicationManifest: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: components["parameters"]["IfMatchOptional"];
            };
            path: {
                applicationKey: components["parameters"]["ApplicationKey"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["application-manifest.schema"];
            };
        };
        responses: {
            /** @description 登録した manifest */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["application-manifest.schema"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            412: components["responses"]["PreconditionFailed"];
        };
    };
    getFeedbackReviewContext: {
        parameters: {
            query: {
                applicationKey: components["parameters"]["ApplicationKeyQuery"];
                environmentKey: components["parameters"]["EnvironmentKeyQuery"];
                externalWorkspaceKey: components["parameters"]["ExternalWorkspaceKeyQuery"];
                release: string;
                locale?: string;
                pageKey: string;
                routeTemplate: string;
                /** @description JSON object として直列化した path parameter。 */
                pathParameters: string;
                /** @description JSON object として直列化した許可候補 query parameter。 */
                queryParameters?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 現在位置へ適用するレビュー文脈 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackReviewContextV1"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listFeedbackSessions: {
        parameters: {
            query: {
                applicationKey: components["parameters"]["ApplicationKeyQuery"];
                environmentKey: components["parameters"]["EnvironmentKeyQuery"];
                externalWorkspaceKey: components["parameters"]["ExternalWorkspaceKeyQuery"];
                status?: components["schemas"]["FeedbackSessionStatus"];
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description セッション一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackSessionPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createFeedbackSession: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackSessionCreateRequest"];
            };
        };
        responses: {
            /** @description 作成したセッション */
            201: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackSessionV1"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    getFeedbackSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description セッション詳細 */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackSessionV1"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    patchFeedbackSession: {
        parameters: {
            query?: never;
            header: {
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["FeedbackSessionPatchRequest"];
            };
        };
        responses: {
            /** @description 更新したセッション */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackSessionV1"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["PreconditionFailed"];
        };
    };
    listFeedbackThreads: {
        parameters: {
            query?: {
                status?: components["schemas"]["FeedbackThreadStatus"];
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description スレッド一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackThreadPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createFeedbackThread: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackThreadCreateRequest"];
            };
        };
        responses: {
            /** @description 作成したスレッド */
            201: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackThreadV1"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["PayloadTooLarge"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getFeedbackThread: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                threadId: components["parameters"]["ThreadId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description スレッド詳細 */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackThreadV1"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getFeedbackThreadDeepLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                threadId: components["parameters"]["ThreadId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 登録済みenvironment/manifestから生成した対象アプリURL */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackDeepLink"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createFeedbackMessage: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                threadId: components["parameters"]["ThreadId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackMessageCreateRequest"];
            };
        };
        responses: {
            /** @description 作成したメッセージ */
            201: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackMessageV1"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    patchFeedbackMessage: {
        parameters: {
            query?: never;
            header: {
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                messageId: components["parameters"]["MessageId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["FeedbackMessagePatchRequest"];
            };
        };
        responses: {
            /** @description 更新したメッセージ */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackMessageV1"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            412: components["responses"]["PreconditionFailed"];
        };
    };
    listFeedbackMessageVersions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                messageId: components["parameters"]["MessageId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description メッセージ版履歴 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackMessageVersionV1"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    patchFeedbackThreadStatus: {
        parameters: {
            query?: never;
            header: {
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                threadId: components["parameters"]["ThreadId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/merge-patch+json": {
                    status: components["schemas"]["FeedbackThreadStatus"];
                };
            };
        };
        responses: {
            /** @description 更新したスレッド */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackThreadV1"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            412: components["responses"]["PreconditionFailed"];
        };
    };
    getFeedbackEvidence: {
        parameters: {
            query?: never;
            header?: {
                Range?: components["parameters"]["Range"];
            };
            path: {
                threadId: components["parameters"]["ThreadId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 認可済み証跡画像 */
            200: {
                headers: {
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "image/png": string;
                    "image/webp": string;
                };
            };
            /** @description Rangeで指定したprivate evidenceの一部 */
            206: {
                headers: {
                    "Content-Range"?: string;
                    "Accept-Ranges"?: "bytes";
                    [name: string]: unknown;
                };
                content: {
                    "image/png": string;
                    "image/webp": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            416: components["responses"]["RangeNotSatisfiable"];
        };
    };
    createFeedbackExport: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackExportRequest"];
            };
        };
        responses: {
            /** @description 受付済み export job */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackExportJob"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getFeedbackExport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exportId: components["parameters"]["ExportId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description export job の現在状態 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackExportJob"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    downloadFeedbackExport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exportId: components["parameters"]["ExportId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 認可済みで保存期限内のCSV/XLSX */
            200: {
                headers: {
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getFeedbackBackupPolicy: {
        parameters: {
            query: {
                applicationKey: components["parameters"]["ApplicationKeyQuery"];
                externalWorkspaceKey: components["parameters"]["ExternalWorkspaceKeyQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description workspaceの自動証跡バックアップ方針 */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackBackupPolicyView"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    patchFeedbackBackupPolicy: {
        parameters: {
            query: {
                applicationKey: components["parameters"]["ApplicationKeyQuery"];
                externalWorkspaceKey: components["parameters"]["ExternalWorkspaceKeyQuery"];
            };
            header: {
                "If-Match": components["parameters"]["IfMatch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["FeedbackBackupPolicy"];
            };
        };
        responses: {
            /** @description 更新した自動バックアップ方針 */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackBackupPolicyView"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            412: components["responses"]["PreconditionFailed"];
        };
    };
    listFeedbackBackups: {
        parameters: {
            query: {
                applicationKey: components["parameters"]["ApplicationKeyQuery"];
                externalWorkspaceKey: components["parameters"]["ExternalWorkspaceKeyQuery"];
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 自動バックアップ実行履歴 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackBackupRunPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getFeedbackBackup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                backupId: components["parameters"]["BackupId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 自動バックアップ実行状態 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackBackupRun"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    downloadFeedbackBackup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                backupId: components["parameters"]["BackupId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description manifest・CSV・証跡画像を含む自己完結ZIP */
            200: {
                headers: {
                    "Content-Disposition"?: string;
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/zip": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    retryFeedbackBackup: {
        parameters: {
            query: {
                applicationKey: components["parameters"]["ApplicationKeyQuery"];
                externalWorkspaceKey: components["parameters"]["ExternalWorkspaceKeyQuery"];
            };
            header?: never;
            path: {
                backupId: components["parameters"]["BackupId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 再試行待ちへ戻したバックアップ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackBackupRun"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getFeedbackRetentionPolicy: {
        parameters: {
            query: {
                applicationKey: components["parameters"]["ApplicationKeyQuery"];
                externalWorkspaceKey: components["parameters"]["ExternalWorkspaceKeyQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 保存方針 */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackRetentionPolicy"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    patchFeedbackRetentionPolicy: {
        parameters: {
            query: {
                applicationKey: components["parameters"]["ApplicationKeyQuery"];
                externalWorkspaceKey: components["parameters"]["ExternalWorkspaceKeyQuery"];
            };
            header: {
                "If-Match": components["parameters"]["IfMatch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["FeedbackRetentionPolicy"];
            };
        };
        responses: {
            /** @description 更新した保存方針 */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackRetentionPolicy"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            412: components["responses"]["PreconditionFailed"];
        };
    };
    getFeedbackNotificationSettings: {
        parameters: {
            query: {
                applicationKey: components["parameters"]["ApplicationKeyQuery"];
                externalWorkspaceKey: components["parameters"]["ExternalWorkspaceKeyQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 通知接続設定 */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackNotificationSettings"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    patchFeedbackNotificationSettings: {
        parameters: {
            query: {
                applicationKey: components["parameters"]["ApplicationKeyQuery"];
                externalWorkspaceKey: components["parameters"]["ExternalWorkspaceKeyQuery"];
            };
            header: {
                "If-Match": components["parameters"]["IfMatch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["FeedbackNotificationSettings"];
            };
        };
        responses: {
            /** @description 更新した通知接続設定 */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackNotificationSettings"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            412: components["responses"]["PreconditionFailed"];
        };
    };
    listFeedbackConnectorTypes: {
        parameters: {
            query: {
                applicationKey: components["parameters"]["ApplicationKeyQuery"];
                externalWorkspaceKey: components["parameters"]["ExternalWorkspaceKeyQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description platform operatorが登録した別プロセス通知コネクタ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackConnectorType"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listFeedbackNotificationConnectors: {
        parameters: {
            query: {
                applicationKey: components["parameters"]["ApplicationKeyQuery"];
                externalWorkspaceKey: components["parameters"]["ExternalWorkspaceKeyQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description workspaceの通知コネクタ一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackNotificationConnector"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createFeedbackNotificationConnector: {
        parameters: {
            query: {
                applicationKey: components["parameters"]["ApplicationKeyQuery"];
                externalWorkspaceKey: components["parameters"]["ExternalWorkspaceKeyQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackNotificationConnectorCreateRequest"];
            };
        };
        responses: {
            /** @description 追加した通知コネクタ */
            201: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackNotificationConnector"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    deleteFeedbackNotificationConnector: {
        parameters: {
            query: {
                applicationKey: components["parameters"]["ApplicationKeyQuery"];
                externalWorkspaceKey: components["parameters"]["ExternalWorkspaceKeyQuery"];
            };
            header: {
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                connectorId: components["parameters"]["ConnectorId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 通知コネクタを削除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            412: components["responses"]["PreconditionFailed"];
        };
    };
    patchFeedbackNotificationConnector: {
        parameters: {
            query: {
                applicationKey: components["parameters"]["ApplicationKeyQuery"];
                externalWorkspaceKey: components["parameters"]["ExternalWorkspaceKeyQuery"];
            };
            header: {
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                connectorId: components["parameters"]["ConnectorId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["FeedbackNotificationConnectorPatchRequest"];
            };
        };
        responses: {
            /** @description 更新した通知コネクタ */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackNotificationConnector"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["PreconditionFailed"];
        };
    };
    listFeedbackWorkspaceMemberships: {
        parameters: {
            query: {
                applicationKey: components["parameters"]["ApplicationKeyQuery"];
                externalWorkspaceKey: components["parameters"]["ExternalWorkspaceKeyQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description workspace membership 一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackWorkspaceMember"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createFeedbackWorkspaceMembership: {
        parameters: {
            query: {
                applicationKey: components["parameters"]["ApplicationKeyQuery"];
                externalWorkspaceKey: components["parameters"]["ExternalWorkspaceKeyQuery"];
            };
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackMembershipCreateRequest"];
            };
        };
        responses: {
            /** @description 追加したmembership */
            201: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackWorkspaceMember"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            416: components["responses"]["RangeNotSatisfiable"];
        };
    };
    deleteFeedbackWorkspaceMembership: {
        parameters: {
            query: {
                applicationKey: components["parameters"]["ApplicationKeyQuery"];
                externalWorkspaceKey: components["parameters"]["ExternalWorkspaceKeyQuery"];
            };
            header: {
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description membershipを削除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["PreconditionFailed"];
        };
    };
    patchFeedbackWorkspaceMembership: {
        parameters: {
            query: {
                applicationKey: components["parameters"]["ApplicationKeyQuery"];
                externalWorkspaceKey: components["parameters"]["ExternalWorkspaceKeyQuery"];
            };
            header: {
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["FeedbackMembershipPatchRequest"];
            };
        };
        responses: {
            /** @description 更新したmembership */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackWorkspaceMember"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            412: components["responses"]["PreconditionFailed"];
        };
    };
    listFeedbackNotificationDeliveries: {
        parameters: {
            query: {
                applicationKey: components["parameters"]["ApplicationKeyQuery"];
                externalWorkspaceKey: components["parameters"]["ExternalWorkspaceKeyQuery"];
                status?: "pending" | "processing" | "delivered" | "failed";
                connectorId?: string;
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description payload本文とsecretを含まない配送状態・試行履歴 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackNotificationDelivery"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    retryFeedbackNotificationDelivery: {
        parameters: {
            query: {
                applicationKey: components["parameters"]["ApplicationKeyQuery"];
                externalWorkspaceKey: components["parameters"]["ExternalWorkspaceKeyQuery"];
            };
            header?: never;
            path: {
                deliveryId: components["parameters"]["DeliveryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 新しいretry cycleへ戻した配送 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackNotificationDelivery"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
}
