/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getFeedbackCapabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getFeedbackMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{applicationKey}/manifest": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationKey: components["parameters"]["ApplicationKey"];
            };
            cookie?: never;
        };
        get: operations["getFeedbackApplicationManifest"];
        put: operations["putFeedbackApplicationManifest"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review-context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getFeedbackReviewContext"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listFeedbackSessions"];
        put?: never;
        post: operations["createFeedbackSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get: operations["getFeedbackSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["patchFeedbackSession"];
        trace?: never;
    };
    "/sessions/{sessionId}/threads": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get: operations["listFeedbackThreads"];
        put?: never;
        post: operations["createFeedbackThread"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/threads/{threadId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                threadId: components["parameters"]["ThreadId"];
            };
            cookie?: never;
        };
        get: operations["getFeedbackThread"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/threads/{threadId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                threadId: components["parameters"]["ThreadId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createFeedbackMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages/{messageId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                messageId: components["parameters"]["MessageId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["patchFeedbackMessage"];
        trace?: never;
    };
    "/messages/{messageId}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                messageId: components["parameters"]["MessageId"];
            };
            cookie?: never;
        };
        get: operations["listFeedbackMessageVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/threads/{threadId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                threadId: components["parameters"]["ThreadId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["patchFeedbackThreadStatus"];
        trace?: never;
    };
    "/threads/{threadId}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                threadId: components["parameters"]["ThreadId"];
            };
            cookie?: never;
        };
        get: operations["getFeedbackEvidence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createFeedbackExport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/retention-policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getFeedbackRetentionPolicy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["patchFeedbackRetentionPolicy"];
        trace?: never;
    };
    "/notification-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getFeedbackNotificationSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["patchFeedbackNotificationSettings"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        FeedbackApplicationManifestV1: components["schemas"]["application-manifest.schema"];
        FeedbackLocationV1: components["schemas"]["location.schema"];
        FeedbackTargetV1: components["schemas"]["target.schema"];
        FeedbackWebhookEventV1: components["schemas"]["webhook-event.schema"];
        FeedbackCapabilities: {
            /** @constant */
            apiVersion: "1.0";
            /** @constant */
            apiMajorVersion: 1;
            manifestSchemaVersions: "1"[];
            targetSchemaVersions: "1"[];
            evidence: {
                maxBytes: number;
                acceptedContentTypes: ("image/png" | "image/webp")[];
            };
            features: string[];
        };
        FeedbackProblem: {
            /** Format: uri-reference */
            type: string;
            title: string;
            status: number;
            detail?: string;
            code: string;
            requestId: string;
        };
        /** @enum {unknown} */
        FeedbackPermission: "feedback.read" | "feedback.comment" | "feedback.manage" | "feedback.admin";
        FeedbackParticipant: {
            principalId: string;
            displayName?: string | null;
            participantName?: string | null;
        };
        FeedbackMembership: {
            applicationKey: string;
            externalWorkspaceKey: string;
            permissions: components["schemas"]["FeedbackPermission"][];
        };
        FeedbackMe: {
            participant: components["schemas"]["FeedbackParticipant"];
            memberships: components["schemas"]["FeedbackMembership"][];
        };
        FeedbackHostContextV1: {
            /** @constant */
            schemaVersion: "1";
            applicationKey: string;
            environmentKey: string;
            externalWorkspaceKey: string;
            release: string;
            locale?: string;
        };
        FeedbackParticipantPolicy: {
            /** @constant */
            mode: "authenticated-identity";
        } | {
            /** @enum {unknown} */
            mode: "prompt" | "authenticated-and-prompt";
            /** @enum {unknown} */
            storage: "memory" | "local-storage" | "host";
        };
        FeedbackEvidencePolicy: {
            enabled: boolean;
            maxBytes: number;
            acceptedContentTypes: ("image/png" | "image/webp")[];
        };
        FeedbackReviewContextV1: {
            session: components["schemas"]["FeedbackSessionV1"] | null;
            /** @enum {unknown} */
            scope: "reviewable" | "excluded" | "unregistered";
            /** @enum {unknown} */
            posting: "allow" | "warn" | "deny";
            permissions: components["schemas"]["FeedbackPermission"][];
            participantPolicy: components["schemas"]["FeedbackParticipantPolicy"];
            evidencePolicy: components["schemas"]["FeedbackEvidencePolicy"];
        };
        /** @enum {unknown} */
        FeedbackSessionStatus: "draft" | "open" | "closed";
        FeedbackSessionV1: {
            /** Format: uuid */
            id: string;
            applicationKey: string;
            environmentKey: string;
            externalWorkspaceKey: string;
            manifestVersion: string;
            title: string;
            description?: string | null;
            status: components["schemas"]["FeedbackSessionStatus"];
            /** @enum {unknown} */
            outOfScopePosting: "allow" | "warn" | "deny";
            /** Format: date-time */
            startAt?: string | null;
            /** Format: date-time */
            endAt?: string | null;
            scopes: components["schemas"]["FeedbackSessionScopeV1"][];
            perspectives: components["schemas"]["FeedbackSessionPerspectiveV1"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            version: number;
        };
        FeedbackSessionScopeV1: {
            pageKey: string;
            routeTemplate?: string | null;
            reviewable: boolean;
        };
        FeedbackSessionPerspectiveV1: {
            code: string;
            label: string;
            /** @enum {unknown} */
            status: "active" | "future" | "out-of-scope";
            guidance?: string | null;
        };
        FeedbackSessionPage: {
            items: components["schemas"]["FeedbackSessionV1"][];
            nextCursor?: string | null;
            totalCount?: number;
        };
        FeedbackSessionCreateRequest: {
            applicationKey: string;
            environmentKey: string;
            externalWorkspaceKey: string;
            manifestVersion: string;
            title: string;
            description?: string | null;
            /**
             * @default warn
             * @enum {unknown}
             */
            outOfScopePosting: "allow" | "warn" | "deny";
            /** Format: date-time */
            startAt?: string | null;
            /** Format: date-time */
            endAt?: string | null;
            scopes?: components["schemas"]["FeedbackSessionScopeV1"][];
            perspectives?: components["schemas"]["FeedbackSessionPerspectiveV1"][];
        };
        FeedbackSessionPatchRequest: {
            title?: string;
            description?: string | null;
            status?: components["schemas"]["FeedbackSessionStatus"];
            /** @enum {unknown} */
            outOfScopePosting?: "allow" | "warn" | "deny";
            /** Format: date-time */
            startAt?: string | null;
            /** Format: date-time */
            endAt?: string | null;
        };
        /** @enum {unknown} */
        FeedbackThreadStatus: "open" | "resolved";
        FeedbackMessageV1: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            threadId: string;
            author: components["schemas"]["FeedbackParticipant"];
            body: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            editedAt?: string | null;
            version: number;
        };
        FeedbackMessageVersionV1: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            threadId: string;
            author: components["schemas"]["FeedbackParticipant"];
            body: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            editedAt?: string | null;
            version: number;
            current: boolean;
        };
        FeedbackThreadV1: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            sessionId: string;
            displayNumber: number;
            location: components["schemas"]["location.schema"];
            target: components["schemas"]["target.schema"];
            perspectiveCode: string;
            status: components["schemas"]["FeedbackThreadStatus"];
            reporter: components["schemas"]["FeedbackParticipant"];
            /** @default false */
            evidenceAvailable: boolean;
            messages: components["schemas"]["FeedbackMessageV1"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            version: number;
        };
        FeedbackThreadPage: {
            items: components["schemas"]["FeedbackThreadV1"][];
            nextCursor?: string | null;
            totalCount?: number;
        };
        FeedbackThreadCreateRequest: {
            location: components["schemas"]["location.schema"];
            target: components["schemas"]["target.schema"];
            perspectiveCode: string;
            body: string;
            participantName?: string | null;
            evidence?: {
                /** @enum {unknown} */
                contentType: "image/png" | "image/webp";
                dataBase64: string;
                viewportWidth: number;
                viewportHeight: number;
                pixelRatio: number;
                /** Format: date-time */
                capturedAt: string;
            } | null;
        };
        FeedbackMessageCreateRequest: {
            body: string;
            participantName?: string | null;
        };
        FeedbackMessagePatchRequest: {
            body: string;
            participantName?: string | null;
        };
        FeedbackExportRequest: {
            applicationKey: string;
            environmentKey: string;
            externalWorkspaceKey: string;
            /** Format: uuid */
            sessionId?: string | null;
            /** @enum {unknown} */
            format: "csv" | "xlsx";
            /** @default ja-JP */
            locale: string;
            /** @default Asia/Tokyo */
            timezone: string;
        };
        FeedbackExportJob: {
            /** Format: uuid */
            id: string;
            /** @enum {unknown} */
            status: "queued" | "running" | "completed" | "failed";
            /** Format: uri */
            downloadUrl?: string | null;
            /** Format: date-time */
            expiresAt?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        FeedbackRetentionPolicy: {
            evidenceRetentionDays: number | null;
            /** @default 7 */
            exportRetentionDays: number;
        };
        FeedbackNotificationSettings: {
            webhookEnabled: boolean;
            /** Format: uri */
            webhookEndpoint?: string | null;
            /** @default false */
            includeBody: boolean;
            /** @default false */
            includeEvidence: boolean;
        };
        /** FeedbackApplicationManifestV1 */
        "application-manifest.schema": {
            /** @constant */
            schemaVersion: "1";
            applicationKey: string;
            displayName: string;
            manifestVersion: string;
            routes: {
                pageKey: string;
                template: string;
                label: string;
                group?: string;
                parameters?: {
                    [key: string]: {
                        /** @enum {unknown} */
                        persistence: "store" | "hash" | "discard";
                    };
                };
                queryParameters?: {
                    [key: string]: {
                        /** @enum {unknown} */
                        persistence: "store" | "hash" | "discard";
                    };
                };
                aliases?: string[];
            }[];
        };
        /** FeedbackLocationV1 */
        "location.schema": {
            /** @constant */
            schemaVersion: "1";
            pageKey: string;
            routeTemplate: string;
            pathParameters: {
                [key: string]: string;
            };
            queryParameters?: {
                [key: string]: string;
            };
        };
        /** FeedbackTargetV1 */
        "target.schema": {
            /** @constant */
            schemaVersion: "1";
            /** @constant */
            kind: "ui-element";
            elementKey: string;
            relativeX: number;
            relativeY: number;
        } | {
            /** @constant */
            schemaVersion: "1";
            /** @constant */
            kind: "screen-position";
            relativeX: number;
            relativeY: number;
        } | {
            /** @constant */
            schemaVersion: "1";
            /** @constant */
            kind: "map-feature";
            /** @constant */
            provider: "maplibre";
            sourceKey: string;
            sourceLayer?: string;
            featureKey: string;
            longitude: number;
            latitude: number;
        } | {
            /** @constant */
            schemaVersion: "1";
            /** @constant */
            kind: "map-position";
            longitude: number;
            latitude: number;
        };
        /** FeedbackWebhookEventV1 */
        "webhook-event.schema": {
            /** @constant */
            schemaVersion: "1";
            /** Format: uuid */
            eventId: string;
            /** @enum {unknown} */
            eventType: "feedback.thread.created.v1" | "feedback.message.created.v1" | "feedback.thread.resolved.v1" | "feedback.thread.reopened.v1";
            /** Format: date-time */
            occurredAt: string;
            tenantKey: string;
            applicationKey: string;
            environmentKey: string;
            workspaceKey: string;
            /** Format: uuid */
            sessionId: string;
            /** Format: uuid */
            threadId: string;
            actor: {
                principalId: string;
                displayName?: string;
                participantName?: string;
            };
            /** Format: uri */
            deepLink: string;
            body?: string;
            /** @default false */
            evidenceIncluded: boolean;
        };
    };
    responses: {
        /** @description 契約または manifest に適合しない入力 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["FeedbackProblem"];
            };
        };
        /** @description 未認証または token 無効 */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["FeedbackProblem"];
            };
        };
        /** @description feedback permission 不足 */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["FeedbackProblem"];
            };
        };
        /** @description resource 不在または存在秘匿 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["FeedbackProblem"];
            };
        };
        /** @description open session 競合などの一意制約違反 */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["FeedbackProblem"];
            };
        };
        /** @description ETag が古い */
        PreconditionFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["FeedbackProblem"];
            };
        };
        /** @description evidence または request が上限を超えた */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["FeedbackProblem"];
            };
        };
        /** @description rate limit または quota 超過 */
        TooManyRequests: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["FeedbackProblem"];
            };
        };
        /** @description DB または必須依存が利用不能 */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["FeedbackProblem"];
            };
        };
    };
    parameters: {
        ApplicationKey: string;
        ApplicationKeyQuery: string;
        EnvironmentKeyQuery: string;
        ExternalWorkspaceKeyQuery: string;
        SessionId: string;
        ThreadId: string;
        MessageId: string;
        Cursor: string;
        Limit: number;
        IdempotencyKey: string;
        IfMatch: string;
        IfMatchOptional: string;
    };
    requestBodies: never;
    headers: {
        /** @description resource version。更新時は If-Match へそのまま指定する。 */
        ETag: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getFeedbackCapabilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API と schema の対応能力 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackCapabilities"];
                };
            };
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getFeedbackMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 認証主体と workspace 権限 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackMe"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getFeedbackApplicationManifest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationKey: components["parameters"]["ApplicationKey"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 登録済み application manifest */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["application-manifest.schema"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    putFeedbackApplicationManifest: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: components["parameters"]["IfMatchOptional"];
            };
            path: {
                applicationKey: components["parameters"]["ApplicationKey"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["application-manifest.schema"];
            };
        };
        responses: {
            /** @description 登録した manifest */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["application-manifest.schema"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            412: components["responses"]["PreconditionFailed"];
        };
    };
    getFeedbackReviewContext: {
        parameters: {
            query: {
                applicationKey: components["parameters"]["ApplicationKeyQuery"];
                environmentKey: components["parameters"]["EnvironmentKeyQuery"];
                externalWorkspaceKey: components["parameters"]["ExternalWorkspaceKeyQuery"];
                release: string;
                locale?: string;
                pageKey: string;
                routeTemplate: string;
                /** @description JSON object として直列化した path parameter。 */
                pathParameters: string;
                /** @description JSON object として直列化した許可候補 query parameter。 */
                queryParameters?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 現在位置へ適用するレビュー文脈 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackReviewContextV1"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listFeedbackSessions: {
        parameters: {
            query: {
                applicationKey: components["parameters"]["ApplicationKeyQuery"];
                environmentKey: components["parameters"]["EnvironmentKeyQuery"];
                externalWorkspaceKey: components["parameters"]["ExternalWorkspaceKeyQuery"];
                status?: components["schemas"]["FeedbackSessionStatus"];
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description セッション一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackSessionPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createFeedbackSession: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackSessionCreateRequest"];
            };
        };
        responses: {
            /** @description 作成したセッション */
            201: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackSessionV1"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    getFeedbackSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description セッション詳細 */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackSessionV1"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    patchFeedbackSession: {
        parameters: {
            query?: never;
            header: {
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["FeedbackSessionPatchRequest"];
            };
        };
        responses: {
            /** @description 更新したセッション */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackSessionV1"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["PreconditionFailed"];
        };
    };
    listFeedbackThreads: {
        parameters: {
            query?: {
                status?: components["schemas"]["FeedbackThreadStatus"];
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description スレッド一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackThreadPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createFeedbackThread: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackThreadCreateRequest"];
            };
        };
        responses: {
            /** @description 作成したスレッド */
            201: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackThreadV1"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["PayloadTooLarge"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getFeedbackThread: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                threadId: components["parameters"]["ThreadId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description スレッド詳細 */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackThreadV1"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createFeedbackMessage: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                threadId: components["parameters"]["ThreadId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackMessageCreateRequest"];
            };
        };
        responses: {
            /** @description 作成したメッセージ */
            201: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackMessageV1"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    patchFeedbackMessage: {
        parameters: {
            query?: never;
            header: {
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                messageId: components["parameters"]["MessageId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["FeedbackMessagePatchRequest"];
            };
        };
        responses: {
            /** @description 更新したメッセージ */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackMessageV1"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            412: components["responses"]["PreconditionFailed"];
        };
    };
    listFeedbackMessageVersions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                messageId: components["parameters"]["MessageId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description メッセージ版履歴 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackMessageVersionV1"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    patchFeedbackThreadStatus: {
        parameters: {
            query?: never;
            header: {
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                threadId: components["parameters"]["ThreadId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/merge-patch+json": {
                    status: components["schemas"]["FeedbackThreadStatus"];
                };
            };
        };
        responses: {
            /** @description 更新したスレッド */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackThreadV1"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            412: components["responses"]["PreconditionFailed"];
        };
    };
    getFeedbackEvidence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                threadId: components["parameters"]["ThreadId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 認可済み証跡画像 */
            200: {
                headers: {
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "image/png": string;
                    "image/webp": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createFeedbackExport: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackExportRequest"];
            };
        };
        responses: {
            /** @description 受付済み export job */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackExportJob"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getFeedbackRetentionPolicy: {
        parameters: {
            query: {
                applicationKey: components["parameters"]["ApplicationKeyQuery"];
                externalWorkspaceKey: components["parameters"]["ExternalWorkspaceKeyQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 保存方針 */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackRetentionPolicy"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    patchFeedbackRetentionPolicy: {
        parameters: {
            query: {
                applicationKey: components["parameters"]["ApplicationKeyQuery"];
                externalWorkspaceKey: components["parameters"]["ExternalWorkspaceKeyQuery"];
            };
            header: {
                "If-Match": components["parameters"]["IfMatch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["FeedbackRetentionPolicy"];
            };
        };
        responses: {
            /** @description 更新した保存方針 */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackRetentionPolicy"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            412: components["responses"]["PreconditionFailed"];
        };
    };
    getFeedbackNotificationSettings: {
        parameters: {
            query: {
                applicationKey: components["parameters"]["ApplicationKeyQuery"];
                externalWorkspaceKey: components["parameters"]["ExternalWorkspaceKeyQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 通知接続設定 */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackNotificationSettings"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    patchFeedbackNotificationSettings: {
        parameters: {
            query: {
                applicationKey: components["parameters"]["ApplicationKeyQuery"];
                externalWorkspaceKey: components["parameters"]["ExternalWorkspaceKeyQuery"];
            };
            header: {
                "If-Match": components["parameters"]["IfMatch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["FeedbackNotificationSettings"];
            };
        };
        responses: {
            /** @description 更新した通知接続設定 */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackNotificationSettings"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            412: components["responses"]["PreconditionFailed"];
        };
    };
}
